development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:026ff85fb788e148d869f3cc353bcd39@scat.redistogo.com:11443/
  # channel_prefix: province_pharmacy_production
